# Generated by Django 5.1.7 on 2025-03-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assunto", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("mensagem", models.TextField(max_length=1000)),
            ],
        ),
    ]
