# Generated by Django 5.1.6 on 2025-03-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contato", "0002_contato_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contato",
            name="assunto",
            field=models.CharField(
                choices=[
                    ("", "Selecione um assunto"),
                    ("descontos", "Descontos"),
                    ("consultoria", "Consultoria"),
                    ("freelance", "Freelance"),
                    ("elogios", "Elogios"),
                    ("reclamações", "Reclamações"),
                    ("outros", "Outros"),
                ],
                default="",
                max_length=100,
            ),
        ),
    ]
