# Generated by Django 5.1.6 on 2025-03-12 02:08

import datetime
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("autor", models.CharField(max_length=255)),
                ("titulo", models.CharField(max_length=255)),
                ("subtitulo", models.CharField(max_length=255)),
                ("resumo", models.TextField()),
                ("conteudo", django_ckeditor_5.fields.CKEditor5Field()),
                (
                    "imagem_capa",
                    models.ImageField(blank=True, null=True, upload_to="static/blog/"),
                ),
                (
                    "data_publicacao",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 3, 11, 22, 8, 30, 439828)
                    ),
                ),
            ],
        ),
    ]
