# Generated by Django 5.1.6 on 2025-03-12 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="data_publicacao",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 11, 22, 9, 5, 625805)
            ),
        ),
    ]
