# Generated by Django 5.1.7 on 2025-03-15 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_data_publicacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="data_publicacao",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 14, 20, 22, 9, 189159)
            ),
        ),
    ]
