# Generated by Django 5.1.6 on 2025-03-17 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_data_publicacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="data_publicacao",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 17, 12, 18, 47, 437969)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="imagem_capa",
            field=models.ImageField(blank=True, null=True, upload_to="blog/images"),
        ),
    ]
